Update README.md
go-lark/awesome-lark pull request #3
Opened 2022-08-10 06:04 UTC by hilaily

2022-08-11 02:58 UTC, crispgm requested changes

2022-08-11 02:58 UTC, crispgm commented on README.md
> +- [go-lark/docs](https://github.com/go-lark/docs): Feishu/Lark Docs(Doc, SpreadSheet, File etc) API
现在好像改README不顶用了？得改Go代码里面的

2022-08-11 03:21 UTC, hilaily commented on README.md
> +- [go-lark/docs](https://github.com/go-lark/docs): Feishu/Lark Docs(Doc, SpreadSheet, File etc) API
代码里也改了，不知道这里要不要改，所以也保留了一份

2022-08-11 03:24 UTC, crispgm requested changes

2022-08-11 03:24 UTC, crispgm commented on README.md
> +- [go-lark/docs](https://github.com/go-lark/docs): Feishu/Lark Docs(Doc, SpreadSheet, File etc) API
> 代码里也改了，不知道这里要不要改，所以也保留了一份

OK。那这个不用改

2022-10-12 07:55 UTC, crispgm commented
cherry-picked f330e8d3db61b66f8b5032bb02bce08679b1d618

2022-10-12 07:55 UTC, closed without merging